# Test The Saved Retail Price Model

Use this notebook to load `models/best_price_model.joblib` and test your own product values without retraining the model.

In [1]:
from pathlib import Path
import json
import joblib
import pandas as pd

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent

MODEL_PATH = ROOT / "models" / "best_price_model.joblib"
METRICS_PATH = ROOT / "reports" / "model_training_metrics.json"

metrics = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
feature_columns = metrics["numeric_features"] + metrics["categorical_features"]
model = joblib.load(MODEL_PATH)

print("Loaded model:", MODEL_PATH)
print("Required columns:")
feature_columns

Loaded model: C:\Users\gosfe\OneDrive\University\Third year\Second Semester\Machine Learning\Project repo\models\best_price_model.joblib
Required columns:

['order_item_id',
 'freight_value',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'product_volume_cm3',
 'product_demand_count',
 'category_demand_count',
 'product_category_name_english',
 'freight_level',
 'product_size_level']

## Option A: Type Your Values Here

Edit the numbers and category values in the cell below, then run the prediction cell. Keep all 15 column names exactly the same.

In [2]:
manual_input = pd.DataFrame([
    {
        "order_item_id": 1,
        "freight_value": 15.50,
        "product_name_lenght": 55,
        "product_description_lenght": 600,
        "product_photos_qty": 3,
        "product_weight_g": 800,
        "product_length_cm": 30,
        "product_height_cm": 10,
        "product_width_cm": 20,
        "product_volume_cm3": 6000,
        "product_demand_count": 10,
        "category_demand_count": 3685,
        "product_category_name_english": "cool_stuff",
        "freight_level": "Medium Freight",
        "product_size_level": "Small",
    }
])

manual_input

,order_item_id,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3,product_demand_count,category_demand_count,product_category_name_english,freight_level,product_size_level
0,1,15.5,55,600,3,800,30,10,20,6000,10,3685,cool_stuff,Medium Freight,Small

In [3]:
predictions = model.predict(manual_input[feature_columns])
manual_input.assign(predicted_price=[round(float(value), 2) for value in predictions])

,order_item_id,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3,product_demand_count,category_demand_count,product_category_name_english,freight_level,product_size_level,predicted_price
0,1,15.5,55,600,3,800,30,10,20,6000,10,3685,cool_stuff,Medium Freight,Small,90.83

## Option B: Edit The CSV Template

You can also edit `dataset/manual_test_input.csv`, add more rows, and run the cell below.

In [4]:
manual_file = ROOT / "dataset" / "manual_test_input.csv"
manual_data = pd.read_csv(manual_file)

missing = [col for col in feature_columns if col not in manual_data.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}")

predictions = model.predict(manual_data[feature_columns])
manual_data.assign(predicted_price=[round(float(value), 2) for value in predictions])

,order_item_id,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3,product_demand_count,category_demand_count,product_category_name_english,freight_level,product_size_level,predicted_price
0,1,15.5,55,600,3,800,30,10,20,6000,10,3685,cool_stuff,Medium Freight,Small,90.83
1,1,30.0,60,900,4,5000,45,25,35,39375,2,1913,pet_shop,High Freight,Large,234.04